$(function(){
	$(".a1").click(function(){
		$(".account").show();
		$(".wddd").hide();
		$(".vip").hide();
		$(".wdjf").hide();
		$(".pmsz").hide();
		$(".address").hide();
		$(".zhxq").hide();
	});
	$(".a2").click(function(){
		$(".account").hide();
		$(".wddd").show();
		$(".vip").hide();
		$(".wdjf").hide();
		$(".pmsz").hide();
		$(".address").hide();
		$(".zhxq").hide();
	});
	$(".a3").click(function(){
		$(".account").hide();
		$(".wddd").hide();
		$(".vip").show();
		$(".wdjf").hide();
		$(".pmsz").hide();
		$(".address").hide();
		$(".zhxq").hide();
	});
	$(".a4").click(function(){
		$(".account").hide();
		$(".wddd").hide();
		$(".vip").hide();
		$(".wdjf").show();
		$(".pmsz").hide();
		$(".address").hide();
		$(".zhxq").hide();
	});
	$(".a5").click(function(){
		$(".account").hide();
		$(".wddd").hide();
		$(".vip").hide();
		$(".wdjf").hide();
		$(".pmsz").show();
		$(".address").hide();
		$(".zhxq").hide();
	});
	$(".a6").click(function(){
		$(".account").hide();
		$(".wddd").hide();
		$(".vip").hide();
		$(".wdjf").hide();
		$(".pmsz").hide();
		$(".address").show();
		$(".zhxq").hide();
	});
	$(".a7").click(function(){
		$(".account").hide();
		$(".wddd").hide();
		$(".vip").hide();
		$(".wdjf").hide();
		$(".pmsz").hide();
		$(".address").hide();
		$(".zhxq").show();
	});
})